# Generated by Django 6.0.1 on 2026-03-15 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0038_tenant_logo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Store",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=150)),
                        ("code", models.CharField(blank=True, max_length=50, null=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "db_table": "store_store",
                    },
                ),
                migrations.CreateModel(
                    name="Tenant",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                        ("name", models.CharField(max_length=150)),
                        ("slug", models.SlugField(max_length=150, unique=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "db_table": "store_tenant",
                    },
                ),
                migrations.CreateModel(
                    name="Branch",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=150)),
                        ("code", models.CharField(blank=True, max_length=50, null=True)),
                        ("address", models.CharField(blank=True, default="", max_length=200)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="client.store")),
                    ],
                    options={
                        "db_table": "store_branch",
                        "unique_together": {("store", "code")},
                    },
                ),
                migrations.AddField(
                    model_name="store",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stores", to="client.tenant"),
                ),
                migrations.CreateModel(
                    name="UserOnboarding",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active")], default="pending", max_length=20)),
                        ("requested_at", models.DateTimeField(auto_now_add=True)),
                        ("activated_at", models.DateTimeField(blank=True, null=True)),
                        ("activated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activated_users", to=settings.AUTH_USER_MODEL)),
                        ("assigned_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="onboarded_users", to="client.branch")),
                        ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_requests", to="client.store")),
                        ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_requests", to="client.tenant")),
                        ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "store_useronboarding",
                    },
                ),
                migrations.CreateModel(
                    name="BranchMember",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("role", models.CharField(choices=[("admin", "Admin"), ("manager", "Manager"), ("staff", "Staff")], default="staff", max_length=20)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="client.branch")),
                        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="branch_memberships", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "store_branchmember",
                        "unique_together": {("branch", "user")},
                    },
                ),
                migrations.CreateModel(
                    name="StoreMember",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("role", models.CharField(choices=[("admin", "Admin"), ("manager", "Manager"), ("staff", "Staff")], default="staff", max_length=20)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="client.store")),
                        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_memberships", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "store_storemember",
                        "unique_together": {("store", "user")},
                    },
                ),
                migrations.AlterUniqueTogether(
                    name="store",
                    unique_together={("tenant", "code")},
                ),
                migrations.CreateModel(
                    name="TenantMember",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("manager", "Manager"), ("staff", "Staff")], default="staff", max_length=20)),
                        ("is_owner", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="client.tenant")),
                        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_memberships", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "store_tenantmember",
                        "unique_together": {("tenant", "user")},
                    },
                ),
            ],
        ),
    ]
