# Generated by Django 6.0.1 on 2026-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
