# Generated by Django 5.1.7 on 2025-04-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('item_price', models.CharField(blank=True, max_length=200, null=True)),
                ('package_price', models.CharField(blank=True, max_length=200, null=True)),
                ('item_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('package_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.customer')),
                ('product', models.ManyToManyField(related_name='products', to='store.products')),
            ],
        ),
    ]
