# Generated by Django 5.1.7 on 2025-04-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.CharField(blank=True, max_length=200, null=True)),
                ('package_price', models.CharField(blank=True, max_length=200, null=True)),
                ('item_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('package_qty', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ManyToManyField(related_name='products', to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('total_value', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='store.salesproducts')),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
