# Generated by Django 5.1.7 on 2025-04-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_salesproducts_salesdetails_delete_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetails',
            old_name='total_value',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesdetails',
            name='sale',
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='paid_amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='unpaid_amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesproducts',
            name='sale_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='store.salesdetails'),
            preserve_default=False,
        ),
    ]
