# Generated by Django 5.1.7 on 2025-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_total_value_salesdetails_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='total_items',
            new_name='num_items',
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
