# Generated by Django 5.1.7 on 2025-04-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='salesproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produts', to='store.products'),
        ),
    ]
