# Generated by Django 5.1.7 on 2025-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_salesproducts_product_salesproducts_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillNumberTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
