# Generated by Django 5.2 on 2025-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_expense_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='OtherIncome',
        ),
    ]
