# Generated by Django 5.2 on 2025-04-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_expense_delete_otherincome'),
    ]

    operations = [
    ]
