# Generated by Django 5.2.1 on 2025-05-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_expense_otherincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_weight_base', models.BooleanField(default=False)),
                ('conversion_to_base', models.FloatField(blank=True, help_text='Conversion factor to the base unit (e.g., 7 for Sir if base is KG). Leave blank if conversion is product-specific.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.baseunit'),
        ),
    ]
