# Generated by Django 5.2.1 on 2025-05-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_baseunit_products_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.purchaseunit'),
        ),
    ]
