# Generated by Django 5.2.1 on 2025-07-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_exchangerate_remove_products_num_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='package_sale_price_afn',
            new_name='package_sale_price',
        ),
    ]
