# Generated by Django 5.2.1 on 2025-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_package_sale_price_afn_products_package_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='usd_package_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
