# Generated by Django 5.2.1 on 2025-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_products_usd_package_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
