# Generated by Django 6.0.1 on 2026-01-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_products_num_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='num_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
