# Generated by Django 6.0.1 on 2026-02-09 00:00

from django.db import migrations, models
import django.db.models.deletion


def set_currency_category(apps, schema_editor):
    Products = apps.get_model("store", "Products")
    PurchaseUnit = apps.get_model("store", "PurchaseUnit")

    purchase_unit_map = {
        unit.id: (unit.code or "").lower()
        for unit in PurchaseUnit.objects.all()
    }

    for product in Products.objects.select_related(None).all():
        code = purchase_unit_map.get(product.purchase_unit_id, "")
        product.currency_category = "usd" if code == "usd" else "afn"
        product.save(update_fields=["currency_category"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_useronboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseunit",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the base unit this converts to (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_units",
                to="store.baseunit",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="currency_category",
            field=models.CharField(
                choices=[("usd", "USD"), ("afn", "AFN")],
                default="afn",
                max_length=3,
            ),
        ),
        migrations.RunPython(set_currency_category, migrations.RunPython.noop),
    ]
