# Generated by Django 6.0.1 on 2026-02-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_baseunit_currency_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("admin", "Admin"), ("manager", "Manager"), ("staff", "Staff")], default="staff", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="store.store")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("store", "user")},
            },
        ),
        migrations.CreateModel(
            name="StoreStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stock", models.IntegerField(default=0)),
                ("num_of_packages", models.IntegerField(default=0)),
                ("num_items", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_stocks", to="store.products")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_levels", to="store.store")),
            ],
            options={
                "unique_together": {("store", "product")},
            },
        ),
        migrations.CreateModel(
            name="TenantStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stock", models.IntegerField(default=0)),
                ("num_of_packages", models.IntegerField(default=0)),
                ("num_items", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_stocks", to="store.products")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_levels", to="store.tenant")),
            ],
            options={
                "unique_together": {("tenant", "product")},
            },
        ),
        migrations.CreateModel(
            name="InventoryTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_scope", models.CharField(choices=[("tenant", "Tenant"), ("store", "Store"), ("branch", "Branch")], max_length=20)),
                ("to_scope", models.CharField(choices=[("tenant", "Tenant"), ("store", "Store"), ("branch", "Branch")], max_length=20)),
                ("package_qty", models.IntegerField(default=0)),
                ("item_qty", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_transfers", to=settings.AUTH_USER_MODEL)),
                ("from_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_out", to="store.branch")),
                ("from_store", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_out", to="store.store")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_transfers", to="store.products")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_transfers", to="store.tenant")),
                ("to_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_in", to="store.branch")),
                ("to_store", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_in", to="store.store")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(choices=[("tenant", "Tenant"), ("store", "Store"), ("branch", "Branch")], max_length=20)),
                ("movement_type", models.CharField(choices=[("purchase", "Purchase"), ("transfer_in", "Transfer In"), ("transfer_out", "Transfer Out"), ("adjustment", "Adjustment")], max_length=20)),
                ("package_qty", models.IntegerField(default=0)),
                ("item_qty", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to="store.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="store.products")),
                ("store", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to="store.store")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="store.tenant")),
                ("transfer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movements", to="store.inventorytransfer")),
            ],
        ),
    ]
