# Generated by Django 6.0.1 on 2026-02-18 07:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from decimal import InvalidOperation
from django.conf import settings
from django.db import migrations, models


def _to_decimal(value):
    if value in (None, ""):
        return Decimal("0.00")
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError, TypeError):
        return Decimal("0.00")


def _to_int(value):
    if value in (None, ""):
        return 0
    try:
        return int(Decimal(str(value)))
    except (InvalidOperation, ValueError, TypeError):
        return 0


def normalize_legacy_numeric_fields(apps, schema_editor):
    SalesDetails = apps.get_model("store", "SalesDetails")
    SalesProducts = apps.get_model("store", "SalesProducts")
    CustomerPayment = apps.get_model("store", "CustomerPayment")

    for sale in SalesDetails.objects.all().only("id", "total_amount", "paid_amount", "unpaid_amount"):
        sale.total_amount = _to_decimal(sale.total_amount)
        sale.paid_amount = _to_decimal(sale.paid_amount)
        sale.unpaid_amount = _to_decimal(sale.unpaid_amount)
        sale.save(update_fields=["total_amount", "paid_amount", "unpaid_amount"])

    for line in SalesProducts.objects.all().only("id", "item_price", "package_price", "total_price", "item_qty", "package_qty"):
        line.item_price = _to_decimal(line.item_price)
        line.package_price = _to_decimal(line.package_price)
        line.total_price = _to_decimal(line.total_price)
        line.item_qty = _to_int(line.item_qty)
        line.package_qty = _to_int(line.package_qty)
        line.save(update_fields=["item_price", "package_price", "total_price", "item_qty", "package_qty"])

    for payment in CustomerPayment.objects.all().only("id", "payment_amount"):
        payment.payment_amount = _to_int(payment.payment_amount)
        payment.save(update_fields=["payment_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_inventory_scope_and_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=200, null=True),
        ),
        migrations.RunPython(normalize_legacy_numeric_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='unpaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='item_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='package_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproducts',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='store.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='store.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='store.tenant')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.ledgeraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='store.tenant')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='store.ledgeraccount')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_ledger_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_ledger_name_per_tenant'),
        ),
    ]
