# Generated by Django 6.0.1 on 2026-03-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_tenant_logo"),
        ("client", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="inventorytransfer",
                    name="from_branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_out", to="client.branch"),
                ),
                migrations.RemoveField(
                    model_name="branchmember",
                    name="branch",
                ),
                migrations.AlterField(
                    model_name="journalentry",
                    name="branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journal_entries", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="inventorytransfer",
                    name="to_branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_in", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="otherincome",
                    name="branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="other_incomes", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="inventorymovement",
                    name="branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="branchstock",
                    name="branch",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_levels", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="stocktransfer",
                    name="from_branch",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_transfers_out", to="client.branch"),
                ),
                migrations.RemoveField(
                    model_name="customerpayment",
                    name="branch",
                ),
                migrations.AlterField(
                    model_name="expense",
                    name="branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expenses", to="client.branch"),
                ),
                migrations.RemoveField(
                    model_name="useronboarding",
                    name="assigned_branch",
                ),
                migrations.AlterField(
                    model_name="stocktransfer",
                    name="to_branch",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_transfers_in", to="client.branch"),
                ),
                migrations.AlterField(
                    model_name="salesdetails",
                    name="branch",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_details", to="client.branch"),
                ),
                migrations.AlterUniqueTogether(
                    name="branchmember",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="branchmember",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="customer",
                    name="tenant",
                ),
                migrations.AlterField(
                    model_name="salesdetails",
                    name="customer",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer", to="customer.customer"),
                ),
                migrations.RemoveField(
                    model_name="customerpayment",
                    name="customer",
                ),
                migrations.RemoveField(
                    model_name="customerpayment",
                    name="tenant",
                ),
                migrations.AlterUniqueTogether(
                    name="store",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="store",
                    name="tenant",
                ),
                migrations.RemoveField(
                    model_name="useronboarding",
                    name="store",
                ),
                migrations.AlterField(
                    model_name="inventorytransfer",
                    name="to_store",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_in", to="client.store"),
                ),
                migrations.AlterField(
                    model_name="inventorymovement",
                    name="store",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to="client.store"),
                ),
                migrations.AlterField(
                    model_name="inventorytransfer",
                    name="from_store",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transfers_out", to="client.store"),
                ),
                migrations.AlterField(
                    model_name="journalentry",
                    name="store",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journal_entries", to="client.store"),
                ),
                migrations.RemoveField(
                    model_name="storemember",
                    name="store",
                ),
                migrations.AlterField(
                    model_name="storestock",
                    name="store",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_levels", to="client.store"),
                ),
                migrations.AlterUniqueTogether(
                    name="storemember",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="storemember",
                    name="user",
                ),
                migrations.AlterField(
                    model_name="tenantstock",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_levels", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="inventorytransfer",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_transfers", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="salesdetails",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sales_details", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="exchangerate",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="exchange_rates", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="products",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="products", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="category",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="purchaseunit",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="purchase_units", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="journalentry",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="journal_entries", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="ledgeraccount",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_accounts", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="inventorymovement",
                    name="tenant",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="billnumbertracker",
                    name="tenant",
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="bill_tracker", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="baseunit",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="base_units", to="client.tenant"),
                ),
                migrations.AlterField(
                    model_name="otherincome",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="other_incomes", to="client.tenant"),
                ),
                migrations.RemoveField(
                    model_name="useronboarding",
                    name="tenant",
                ),
                migrations.RemoveField(
                    model_name="tenantmember",
                    name="tenant",
                ),
                migrations.AlterField(
                    model_name="expense",
                    name="tenant",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="client.tenant"),
                ),
                migrations.AlterUniqueTogether(
                    name="tenantmember",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="tenantmember",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="useronboarding",
                    name="activated_by",
                ),
                migrations.RemoveField(
                    model_name="useronboarding",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="Branch",
                ),
                migrations.DeleteModel(
                    name="BranchMember",
                ),
                migrations.DeleteModel(
                    name="Customer",
                ),
                migrations.DeleteModel(
                    name="CustomerPayment",
                ),
                migrations.DeleteModel(
                    name="Store",
                ),
                migrations.DeleteModel(
                    name="StoreMember",
                ),
                migrations.DeleteModel(
                    name="Tenant",
                ),
                migrations.DeleteModel(
                    name="TenantMember",
                ),
                migrations.DeleteModel(
                    name="UserOnboarding",
                ),
            ],
        ),
    ]
