# Generated by Django 6.0.1 on 2026-03-18 09:28

from decimal import Decimal

from django.db import migrations, models


def backfill_salesdetails_payable_amount(apps, schema_editor):
    SalesDetails = apps.get_model("store", "SalesDetails")
    SalesDetails.objects.filter(payable_amount=Decimal("0.00")).update(payable_amount=models.F("total_amount"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_rehome_models_to_client_and_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='carried_forward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.RunPython(backfill_salesdetails_payable_amount, noop_reverse),
    ]
