# Generated by Django 6.0.1 on 2026-03-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("store", "0038_tenant_logo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Customer",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(blank=True, default="Walk-in Customer", max_length=200, null=True)),
                        ("phone", models.IntegerField(blank=True, default=0, null=True)),
                        ("address", models.CharField(blank=True, default="------", max_length=200, null=True)),
                        ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="client.tenant")),
                    ],
                    options={
                        "db_table": "store_customer",
                    },
                ),
                migrations.CreateModel(
                    name="CustomerPayment",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("payment_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                        ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer"), ("hesab_pay", "Hesab Pay"), ("hawala", "Hawala")], default="cash", max_length=255)),
                        ("note", models.TextField(blank=True, max_length=255, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_payments", to="client.branch")),
                        ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="customer.customer")),
                        ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="customer_payments", to="client.tenant")),
                    ],
                    options={
                        "db_table": "store_customerpayment",
                    },
                ),
            ],
        ),
    ]
